shellcheck: fixes errors - signed-off-by: trimstray <trimstray@gmail.com>

diff --git a/src/__init__ b/src/__init__
--- a/src/__init__
+++ b/src/__init__
@@ -87,7 +87,7 @@ function __main__() {
   # of the required commands in the commands array is not found.
   if [[ "$missing_counter" -gt 0 ]] ; then
 
-    printf "not found in PATH: %s\n" "${missing_hash[*]}" >&2
+    printf "not found in PATH: %s\\n" "${missing_hash[*]}" >&2
     _exit_ "1"
 
   fi
@@ -167,7 +167,7 @@ function __main__() {
 
         if [[ "$2" == "-" ]] || [[ ! -z "$2" ]] ; then
 
-          printf "%s: invalid option -- '%s'\n" "$_init_name" "$2"
+          printf "%s: invalid option -- '%s'\\n" "$_init_name" "$2"
           _exit_ "1"
 
         # elif [[ -z "$2" ]] ; then break ; fi
@@ -319,7 +319,8 @@ function __main__() {
           # Remove last '/' for better compatibility.
           i="${i%/}"
 
-          _ssl_cert_stack=($(find "$i" -maxdepth 1 -type f -printf "%f\n"))
+          # shellcheck disable=SC2207
+          _ssl_cert_stack=($(find "$i" -maxdepth 1 -type f -printf "%f\\n"))
 
           for j in "${_ssl_cert_stack[@]}" ; do
 
